spring:
  jpa:
    generate-ddl: true
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# ---
# spring:
#   profiles: DEV
#   database strings:
# ---
# spring:
#   profiles: QA
#   database strings: